# Generated by Django 4.1.6 on 2023-02-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of product')),
                ('description', models.TextField(max_length=1000, verbose_name='description of product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price of item')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
